name: PR Quality Gate

on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: UI Test
        run: dotnet test MyGardenPlanner2026.Tests.UI/MyGardenPlanner2026.Tests.UI.csproj --configuration Release --no-build

      - name: Unit Test
        run: dotnet test MyGardenPlanner2026.Tests.Unit/MyGardenPlanner2026.Tests.Unit.csproj --configuration Release --no-build
